name: Update EPG

on:
  schedule:
    # 00:00 UTC = 08:00 AM
    # 12:00 UTC = 08:00 PM
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  grab:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Combine epg.pw
        run: |
          sudo apt-get update && sudo apt-get install -y uuid-runtime
          mkdir -p temp_epg
          
          # Format: "URL|CUSTOM_CHANNEL_ID"
          channels=(
            "https://epg.pw/api/epg.xml?channel_id=562589|mastro.30"
            "https://epg.pw/api/epg.xml?channel_id=3683|mastro.tv1"
            "https://epg.pw/api/epg.xml?channel_id=3711|mastro.tv2"
            "https://epg.pw/api/epg.xml?channel_id=1072|mastro.tv3"
            "https://epg.pw/api/epg.xml?channel_id=1029|mastro.didiktv"
            "https://epg.pw/api/epg.xml?channel_id=1122|mastro.8tv"
            "https://epg.pw/api/epg.xml?channel_id=902|mastro.tv9"
            "https://epg.pw/api/epg.xml?channel_id=2384|mastro.ria"
            "https://epg.pw/api/epg.xml?channel_id=3158|mastro.prima"
            "https://epg.pw/api/epg.xml?channel_id=3145|mastro.oasis"
            "https://epg.pw/api/epg.xml?channel_id=2937|mastro.citra"
            "https://epg.pw/api/epg.xml?channel_id=3784|mastro.rania"
            "https://epg.pw/api/epg.xml?channel_id=3770|mastro.aura"
            "https://epg.pw/api/epg.xml?channel_id=4160|mastro.okey"
            "https://epg.pw/api/epg.xml?channel_id=1584|mastro.alhijrah"
            "https://epg.pw/api/epg.xml?channel_id=3942|mastro.tvs"
            "https://epg.pw/api/epg.xml?channel_id=492816|mastro.channel5"
            "https://epg.pw/api/epg.xml?channel_id=492894|mastro.channel8"
            "https://epg.pw/api/epg.xml?channel_id=492864|mastro.channelu"
            "https://epg.pw/api/epg.xml?channel_id=492901|mastro.suria"
            "https://epg.pw/api/epg.xml?channel_id=3735|mastro.vaanavil"
            "https://epg.pw/api/epg.xml?channel_id=3760|mastro.vellithirai"
            "https://epg.pw/api/epg.xml?channel_id=2058|mastro.vinmeen"
            "https://epg.pw/api/epg.xml?channel_id=2181|mastro.thangathirai"
            "https://epg.pw/api/epg.xml?channel_id=946|mastro.adithya"
            "https://epg.pw/api/epg.xml?channel_id=3325|mastro.colors"
            "https://epg.pw/api/epg.xml?channel_id=2917|mastro.colorstamil"
            "https://epg.pw/api/epg.xml?channel_id=4183|mastro.ktv"
            "https://epg.pw/api/epg.xml?channel_id=543317|mastro.sonyyay"
            "https://epg.pw/api/epg.xml?channel_id=3308|mastro.starvijay"
            "https://epg.pw/api/epg.xml?channel_id=3313|mastro.suntv"
            "https://epg.pw/api/epg.xml?channel_id=4181|mastro.sunlife"
            "https://epg.pw/api/epg.xml?channel_id=3835|mastro.sunmusic"
            "https://epg.pw/api/epg.xml?channel_id=4185|mastro.sunnews"
            "https://epg.pw/api/epg.xml?channel_id=492817|mastro.vasantham"
            "https://epg.pw/api/epg.xml?channel_id=4221|mastro.zeecinema"
            "https://epg.pw/api/epg.xml?channel_id=2885|mastro.zeetamil"
            "https://epg.pw/api/epg.xml?channel_id=543222|mastro.zeethirai"
            "https://epg.pw/api/epg.xml?channel_id=2226|mastro.aec"
            "https://epg.pw/api/epg.xml?channel_id=2124|mastro.aod"
            "https://epg.pw/api/epg.xml?channel_id=1951|mastro.huaheedai"
            "https://epg.pw/api/epg.xml?channel_id=1781|mastro.qj"
            "https://epg.pw/api/epg.xml?channel_id=3518|mastro.cctv4"
            "https://epg.pw/api/epg.xml?channel_id=3885|mastro.ctiasia"
            "https://epg.pw/api/epg.xml?channel_id=3290|mastro.iqiyi"
            "https://epg.pw/api/epg.xml?channel_id=369824|mastro.dramachannel"
            "https://epg.pw/api/epg.xml?channel_id=558518|mastro.beritartm"
            "https://epg.pw/api/epg.xml?channel_id=554726|mastro.daebak"
            "https://epg.pw/api/epg.xml?channel_id=1205|mastro.axn"
            "https://epg.pw/api/epg.xml?channel_id=186250|mastro.hitsnow"
            "https://epg.pw/api/epg.xml?channel_id=3968|mastro.lifetime"
            "https://epg.pw/api/epg.xml?channel_id=3234|mastro.tlc"
            "https://epg.pw/api/epg.xml?channel_id=1889|mastro.kbsworld"
            "https://epg.pw/api/epg.xml?channel_id=2652|mastro.kplus"
            "https://epg.pw/api/epg.xml?channel_id=2323|mastro.tvn"
            "https://epg.pw/api/epg.xml?channel_id=2636|mastro.boo"
            "https://epg.pw/api/epg.xml?channel_id=535446|mastro.famtime"
            "https://epg.pw/api/epg.xml?channel_id=4057|mastro.showcase"
            "https://epg.pw/api/epg.xml?channel_id=517641|mastro.showtime"
            "https://epg.pw/api/epg.xml?channel_id=2280|mastro.ccm"
            "https://epg.pw/api/epg.xml?channel_id=1298|mastro.celestial"
            "https://epg.pw/api/epg.xml?channel_id=2208|mastro.hits"
            "https://epg.pw/api/epg.xml?channel_id=3575|mastro.hitsmovies"
            "https://epg.pw/api/epg.xml?channel_id=543209|mastro.mnplus"
            "https://epg.pw/api/epg.xml?channel_id=543174|mastro.moviesnow"
            "https://epg.pw/api/epg.xml?channel_id=543123|mastro.romedynow"
            "https://epg.pw/api/epg.xml?channel_id=543194|mastro.mnx"
            "https://epg.pw/api/epg.xml?channel_id=517640|mastro.rockaction"
            "https://epg.pw/api/epg.xml?channel_id=517642|mastro.rockxstream"
            "https://epg.pw/api/epg.xml?channel_id=543337|mastro.sonypix"
            "https://epg.pw/api/epg.xml?channel_id=543187|mastro.starmovies"
            "https://epg.pw/api/epg.xml?channel_id=543313|mastro.starmoviesselect"
            "https://epg.pw/api/epg.xml?channel_id=2726|mastro.tvnmovies"
            "https://epg.pw/api/epg.xml?channel_id=997|mastro.afn"
            "https://epg.pw/api/epg.xml?channel_id=4030|mastro.bbcearth"
            "https://epg.pw/api/epg.xml?channel_id=3362|mastro.crimeinvestigation"
            "https://epg.pw/api/epg.xml?channel_id=3437|mastro.discovery"
            "https://epg.pw/api/epg.xml?channel_id=1358|mastro.discoveryasia"
            "https://epg.pw/api/epg.xml?channel_id=465358|mastro.worldfishingnetwork"
            "https://epg.pw/api/epg.xml?channel_id=464884|mastro.natgeowild"
            "https://epg.pw/api/epg.xml?channel_id=524153|mastro.outdoorchannel"
            "https://epg.pw/api/epg.xml?channel_id=3809|mastro.tutortv"
            "https://epg.pw/api/epg.xml?channel_id=3533|mastro.ceria"
            "https://epg.pw/api/epg.xml?channel_id=464755|mastro.boomerang"
            "https://epg.pw/api/epg.xml?channel_id=470691|mastro.disneychannel"
            "https://epg.pw/api/epg.xml?channel_id=464864|mastro.disneyjr"
            "https://epg.pw/api/epg.xml?channel_id=464807|mastro.disneyxd"
            "https://epg.pw/api/epg.xml?channel_id=502308|mastro.jr"
            "https://epg.pw/api/epg.xml?channel_id=464773|mastro.metvtoons"
            "https://epg.pw/api/epg.xml?channel_id=465038|mastro.nicktoons"
            "https://epg.pw/api/epg.xml?channel_id=470709|mastro.treehouse"
            "https://epg.pw/api/epg.xml?channel_id=470671|mastro.ytv"
            "https://epg.pw/api/epg.xml?channel_id=2552|mastro.arena"
            "https://epg.pw/api/epg.xml?channel_id=4100|mastro.arena2"
            "https://epg.pw/api/epg.xml?channel_id=563486|mastro.premierleague3"
            "https://epg.pw/api/epg.xml?channel_id=563485|mastro.premierleague4"
            "https://epg.pw/api/epg.xml?channel_id=539586|mastro.premierleague5"
            "https://epg.pw/api/epg.xml?channel_id=486870|mastro.mutv"
            "https://epg.pw/api/epg.xml?channel_id=486728|mastro.lfctv"
            "https://epg.pw/api/epg.xml?channel_id=465248|mastro.fs1"
            "https://epg.pw/api/epg.xml?channel_id=465280|mastro.fs2"
            "https://epg.pw/api/epg.xml?channel_id=465214|mastro.foxsoccerplus"
            "https://epg.pw/api/epg.xml?channel_id=6317|mastro.skysportsf1"
            "https://epg.pw/api/epg.xml?channel_id=5791|mastro.skysportsfootball"
            "https://epg.pw/api/epg.xml?channel_id=538884|mastro.skysportsgolf"
            "https://epg.pw/api/epg.xml?channel_id=7673|mastro.skysportsmainevent"
            "https://epg.pw/api/epg.xml?channel_id=6958|mastro.skysportspremierleague"
            "https://epg.pw/api/epg.xml?channel_id=219100|mastro.premiersports1"
            "https://epg.pw/api/epg.xml?channel_id=219104|mastro.premiersports2"
            "https://epg.pw/api/epg.xml?channel_id=543110|mastro.ten1"
            "https://epg.pw/api/epg.xml?channel_id=558519|mastro.sukanplus"
            "https://epg.pw/api/epg.xml?channel_id=400477|mastro.tnt1"
            "https://epg.pw/api/epg.xml?channel_id=400480|mastro.tnt2"
            "https://epg.pw/api/epg.xml?channel_id=400479|mastro.tnt3"
            "https://epg.pw/api/epg.xml?channel_id=400478|mastro.tnt4"
            "https://epg.pw/api/epg.xml?channel_id=465006|mastro.usanetwork"
            "https://epg.pw/api/epg.xml?channel_id=465156|mastro.foxdeportes"
          )

          for item in "${channels[@]}"; do
            url="${item%%|*}"
            custom_id="${item#*|}"
            FILENAME="temp_epg/$(uuidgen).xml"
            
            curl -A "Mozilla/5.0" --connect-timeout 30 --retry 5 --retry-delay 5 -sL "$url" > "$FILENAME"
            
            if [ $(stat -c%s "$FILENAME") -lt 100 ]; then
              rm "$FILENAME"
            else
              # Gantikan channel id asal dalam tag <channel id="..."> dan <programme channel="...">
              sed -i -E "s/channel id=\"[^\"]+\"/channel id=\"$custom_id\"/g" "$FILENAME"
              sed -i -E "s/programme channel=\"[^\"]+\"/programme channel=\"$custom_id\"/g" "$FILENAME"
            fi
            sleep 1.2
          done

          echo '<?xml version="1.0" encoding="UTF-8"?>' > epg.xml
          echo '<tv generator-info-name="Gemini-Fixed-EPG">' >> epg.xml
          
          for f in temp_epg/*.xml; do
            sed -n '/<channel/,/<\/channel>/p' "$f" >> epg.xml || true
          done

          for f in temp_epg/*.xml; do
            sed -n '/<programme/,/<\/programme>/p' "$f" | grep -vE '(\?xml|<tv|<\/tv)' >> epg.xml || true
          done
          
          echo '</tv>' >> epg.xml

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          rm -rf temp_epg
          
          git rm mewatch.xml rtmklik.xml vidio.xml indonesia3.xml sooka.xml rctiplus.xml external_epg.xml myepg.xml cignal.xml starhub.xml --ignore-unmatch
          
          git add epg.xml
          
          TIMESTAMP=$(date -u -d "+8 hours" "+%d-%m-%Y %H:%M MYT")
          git commit -m "Update EPG (epg.pw): $TIMESTAMP" || exit 0
          git push
