name: Update Unifi EPG

on:
  schedule:
    - cron: '0 */6 * * *' # Jalan setiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Generate XML
        run: python scripts/unifi_scraper.py

      - name: Push to Repo
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Unifi-Bot"
          git add unifi.xml
          git commit -m "Auto-update unifi.xml: $(date)" || exit 0
          git push
