name: Unifi EPG

on:
  schedule:
    # 23:00 UTC bersamaan jam 7:00 AM waktu Malaysia (UTC+8)
    - cron: '0 23 * * *'
  workflow_dispatch: # Membolehkan anda klik butang 'Run' secara manual

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Latest EPG
        run: |
          curl -s https://raw.githubusercontent.com/walpak1/epg/gh-pages/unifi.xml -o unifi.xml

      - name: Commit and Push
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add unifi.xml
          # Hanya commit jika ada perubahan pada fail
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update EPG: $(date)" && git push)
