name: Update Vidio EPG

on:
  schedule:
    - cron: '0 22 * * *' # Jam 22:00 UTC = Jam 05:00 WIB pagi
  workflow_dispatch: # Tombol manual jika ingin update kapan saja

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python & Library
        run: |
          sudo apt-get update
          pip install requests beautifulsoup4

      - name: Jalankan Script
        run: python fetch_vidio.py

      - name: Upload ke GitHub
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add vidio.xml
          git commit -m "Auto Update EPG $(date)" || exit 0
          git push
